//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco.Cms.Tests.Integration.Umbraco.Examine.Lucene.UmbracoExamine {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFiles() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbraco.Cms.Tests.Integration.Umbraco.Examine.Lucene.UmbracoExamine.TestFiles", typeof(TestFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;media&gt;
        ///	&lt;node id=&quot;1111&quot; version=&quot;902e13f7-5793-482a-9e06-cd94eebd1de0&quot; parentID=&quot;-1&quot; level=&quot;1&quot; writerID=&quot;0&quot; nodeType=&quot;1031&quot; template=&quot;0&quot; sortOrder=&quot;2&quot; createDate=&quot;2010-05-19T15:26:08&quot; updateDate=&quot;2010-05-19T15:26:09&quot; nodeName=&quot;Product Images&quot; urlName=&quot;productimages&quot; writerName=&quot;Administrator&quot; nodeTypeAlias=&quot;Folder&quot; path=&quot;-1,1111&quot;&gt;
        ///		&lt;data alias=&quot;contents&quot;&gt;&lt;/data&gt;
        ///		&lt;node id=&quot;2222&quot; version=&quot;902e13f7-5793-482a-9e06-cd94eebd1de0&quot; parentID=&quot;1111&quot; level=&quot;2&quot; writerID=&quot;0 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE root[ 
        ///&lt;!ELEMENT CWS_Contact ANY&gt;
        ///&lt;!ATTLIST CWS_Contact id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EmailAFriend ANY&gt;
        ///&lt;!ATTLIST CWS_EmailAFriend id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EventItem ANY&gt;
        ///&lt;!ATTLIST CWS_EventItem id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Galleries ANY&gt;
        ///&lt;!ATTLIST CWS_Galleries id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Gallery ANY&gt;
        ///&lt;!ATTLIST CWS_Gallery id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Home ANY&gt;
        ///&lt;!ATTLIST CWS_Home id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_NewsEventsList ANY&gt;        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string umbraco {
            get {
                return ResourceManager.GetString("umbraco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE root[ 
        ///&lt;!ELEMENT CWS_Contact ANY&gt;
        ///&lt;!ATTLIST CWS_Contact id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EmailAFriend ANY&gt;
        ///&lt;!ATTLIST CWS_EmailAFriend id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_EventItem ANY&gt;
        ///&lt;!ATTLIST CWS_EventItem id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Galleries ANY&gt;
        ///&lt;!ATTLIST CWS_Galleries id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Gallery ANY&gt;
        ///&lt;!ATTLIST CWS_Gallery id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_Home ANY&gt;
        ///&lt;!ATTLIST CWS_Home id ID #REQUIRED&gt;
        ///&lt;!ELEMENT CWS_NewsEventsList ANY&gt;        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string umbraco_sort {
            get {
                return ResourceManager.GetString("umbraco_sort", resourceCulture);
            }
        }
    }
}
